= Changelog
All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].




== [2.0.0] - 2020-10-21


=== Changed

* Change the CSS linking with https://gohugo.io/hugo-pipes/introduction/[Hugo Pipes], moving it into the assets folder.
* Update the documentation with additional installations with Hugo Module.


=== Removed

* Web feed templates as they have been moved into its https://github.com/foo-dogsquared/hugo-web-feeds[own theme component].
The removal of the web feed templates marks this update as a breaking change (I think).
* In effect to the removal of the feed templates, `$.Site.Params.feedLimit` is also removed.
But really, I removed it because I recognized https://gohugo.io/templates/rss/#configure-rss[it is a built-in option] in Hugo with `$.Site.Config.Services.RSS.Limit`.
* The recipe section in the README as it is getting too big and also I would argue it should be in its own folder or something.
For now, I'll be putting them in the demo branch as its own section which is better for first-time users.


=== Fixed

* Relative links for multilingual mode.
* Table of contents have conditional rendering made possible with simple CSS (surprisingly).




== [1.2.0] - 2020-05-12


=== Added

* Create a dedicated section for recipes of features in the documentation.

* Add some appropriate `<meta>` tags.

* Add https://dev.twitter.com/cards[Twitter cards] https://opengraphprotocol.org/[Open Graph protocol] with Hugo's internal templates.

* Add `hidden` as a frontmatter option in the page.
This will exclude the page from list templates including the homepage and the theme's web feeds.


=== Changed

* Tweak the appearance of the site a little bit.
The CSS is also improved especially with relative units for consistent margin and padding.

* Improve the web feeds template.




== [1.1.0] - 2020-05-09


=== Added

* Create a theme toggle.
It also [detects with CSS if the user prefers a dark scheme](https://css-tricks.com/dark-modes-with-css/).

* Add a modified date (although requires `.GitInfo` to work which requires a Git-enabled repository).

* Add `toc` to as site and page configuration.
The page config has more priority and can override the site config.


=== Changed

* Update the site to conform with accessibility features.
** Add a `aria-label` for list entries.
** Make the theme screen-reader-friendly with the correct use of [content semantic tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element).
** Revise the color of the links.
** Use viewport units for dynamic font sizes.

* Improve the vertical rhythm of the site.




== [1.0.0] - 2019-09-21 


=== Added

* Create the base layout.
* Add the Asciidoctor content template.
* Create the template for RSS, Atom, and JSON web syndication feeds.
* Implement multilingual mode support.
